name: Build and Release

on:
  push:
    paths:
      - 'package.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check and Setup Haskell Stack
      run: |
        if ! command -v stack &> /dev/null; then
          curl -sSL https://get.haskellstack.org/ | sh
        fi

    - name: Extract Version Info
      run: |
        APP_VERSION=$(grep "^version:" package.yaml | awk '{print $2}')
        GHC_VERSION=$(grep "^resolver:" stack.yaml | awk -F'/' '{print $3}')
        STACK_VERSION=$(stack --version | head -n 1 | awk '{print $2}')
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "GHC_VERSION=$GHC_VERSION" >> $GITHUB_ENV
        echo "STACK_VERSION=$STACK_VERSION" >> $GITHUB_ENV

    - name: Build Project
      run: |
        stack setup
        stack build --system-ghc

    - name: Generate Executable
      run: |
        OUTPUT=$(stack install)
        EXECUTABLE_PATH=$(echo "$OUTPUT" | grep -oP '/home/runner/.local/bin/\K.*')
        echo "EXECUTABLE_PATH=/home/runner/.local/bin/$EXECUTABLE_PATH" >> $GITHUB_ENV

    - name: Rename Executable
      run: mv ${{ env.EXECUTABLE_PATH }} /home/runner/.local/bin/bad-names-v${{ env.APP_VERSION }}

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bad-names-v${{ env.APP_VERSION }}
        path: /home/runner/.local/bin/bad-names-v${{ env.APP_VERSION }}

